# Deep learning
-  The “deep” in “deep learning” isn’t a reference to any kind of deeper understanding achieved by the approach; rather, it stands for this idea of successive layers of representations. 
- Meanwhile, other approaches to machine learning tend to focus on learning only one or two layers of representations of the data (say, taking a pixel histogram and then applying a classification rule); hence, they’re sometimes called shallow learning.

- loss function
- fwd and bwd propagation
- optimizer >>> adjust weight in reverse direction (bwd propagation)
- threshold>> activation function

## Artificial Neural Networks
- using image data

### logistic regression 


In [1]:
!pip install tensorflow

In [49]:
import tensorflow

In [50]:
 from tensorflow.keras.datasets import mnist
 (train_images, train_labels), (test_images, test_labels) = mnist.load_data() #mnist list of numbers in form of image

In [51]:
train_images[0] #it is showing pixels value


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [52]:
train_images[1:3]

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8)

In [53]:
train_labels[1]

0

In [54]:
from PIL import Image # python image learning called pillo 
#to see image
im=Image.fromarray(train_images[1])


In [55]:
im

In [56]:
train_images.shape  #60000 is depth or num of images 28 is x and 28 is y

(60000, 28, 28)

In [57]:
from PIL import Image # python image learning called pillo 
#to see image
km=Image.fromarray(train_images[0])
km

In [58]:
from tensorflow.keras import models 
from tensorflow.keras import layers
model = models.Sequential()
model.add(layers.Dense(512, activation="relu",input_shape=(28*28,))) #(28*28,))) 1 d array
#relu and foftmax are activation function
model.add(layers.Dense(10, activation="softmax"))#activation function =linearity to non linear
#2 layers of sequential (added vertically)
#layer 1 has 512 neurons
#layer 2 has 10 neurons

## before fitting model


In [122]:
from tensorflow.keras.utils import to_categorical #onehotencoder
test_labels_by_cat=to_categorical(test_labels)
train_labels_by_cat=to_categorical(train_labels)
train_labels_by_cat[0]
#model.compile(optimizer="rmsprop",loss="sparse_categorical_crossentropy",metrics=["accuracy"]) ab loss me sparse nhi aye ga

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

 ## before fitting model must be compiled

In [115]:
model.compile(optimizer="rmsprop",loss="sparse_categorical_crossentropy",metrics=["accuracy"]) 

model.compile(optimizer="rmsprop",loss="categorical_crossentropy",metrics=["accuracy"]) 

## data must b e in the shape as the model require

In [116]:
train_images = train_images.reshape((60000, 784))
train_images = train_images.astype("float32") / 255 
#image k pixels ki value 255 tk he. iski data ki range choti krne k liye max se devide kr diya
#take model ka time kam lage data ko normalize kia he
#answer float me aye ga
test_images = test_images.reshape((10000, 784))
test_images = test_images.astype("float32") / 255

In [117]:
train_images[0].shape #reshaped in 1D

(784,)

## Fitting / training the model 

In [121]:
model.compile(optimizer="rmsprop",loss="categorical_crossentropy",metrics=["accuracy"])  


In [120]:
model.fit(train_images, train_labels_by_cat, epochs=5, batch_size=128) 
#batch_size = no. of sample sample +learning size >> Varbose=0,calculation display nhi hogi


Epoch 1/5
469/469 [==============================] - 2s 5ms/step - loss: 2.3020 - accuracy: 0.1110
Epoch 2/5
469/469 [==============================] - 2s 5ms/step - loss: 2.3017 - accuracy: 0.1112
Epoch 3/5
469/469 [==============================] - 2s 5ms/step - loss: 2.3016 - accuracy: 0.1114
Epoch 4/5
469/469 [==============================] - 2s 5ms/step - loss: 2.3017 - accuracy: 0.1119
Epoch 5/5
469/469 [==============================] - 2s 5ms/step - loss: 2.3016 - accuracy: 0.1120


## labels


In [64]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

## model layers summery

In [65]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 512)               401920    
                                                                 
 dense_3 (Dense)             (None, 10)                5130      
                                                                 
Total params: 407050 (1.55 MB)
Trainable params: 407050 (1.55 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [66]:
train_images.shape #28*28 #from 3D to 2D

(60000, 784)

In [67]:
test_digits=test_images[0:10]
pred=model.predict(test_digits)


1/1 [==============================] - 0s 42ms/step


In [68]:
pred

array([[3.05712291e-08, 4.11770795e-09, 3.26115969e-06, 4.22440389e-05,
        1.38881675e-11, 8.82598439e-09, 8.08801648e-13, 9.99953151e-01,
        7.99315316e-08, 1.22859979e-06],
       [9.46433403e-08, 4.26735869e-06, 9.99985456e-01, 8.55919825e-06,
        3.29955735e-13, 7.98146758e-08, 7.53275557e-08, 3.83231641e-13,
        1.42570900e-06, 2.97921925e-13],
       [2.55809567e-07, 9.99486566e-01, 1.13463786e-04, 2.68450594e-06,
        1.26638797e-05, 3.75364175e-06, 1.86124071e-05, 2.46163982e-04,
        1.15602837e-04, 6.78239829e-08],
       [9.99804556e-01, 5.83708193e-09, 2.56867156e-06, 4.28000021e-07,
        8.08952700e-06, 1.27014471e-06, 1.68039784e-04, 8.94966342e-06,
        3.48458995e-09, 6.22222024e-06],
       [1.53938208e-06, 8.57050075e-09, 2.09135646e-06, 8.54391313e-09,
        9.93193090e-01, 7.09852017e-08, 1.06645084e-05, 5.20772955e-05,
        1.25787687e-06, 6.73911674e-03],
       [6.18531937e-09, 9.99883294e-01, 6.43893884e-07, 6.44767368e-08,
   

In [69]:
model.predict(test_digits[[0]])

1/1 [==============================] - 0s 18ms/step


array([[3.05712859e-08, 4.11771595e-09, 3.26115969e-06, 4.22440389e-05,
        1.38881415e-11, 8.82600126e-09, 8.08804683e-13, 9.99953151e-01,
        7.99316808e-08, 1.22859979e-06]], dtype=float32)

In [70]:
import numpy as np

In [71]:
np.argmax(model.predict(test_digits[[0]])) #our data in 2 D

1/1 [==============================] - 0s 18ms/step


7

In [72]:
test_labels[0]

7

In [73]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [74]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 2ms/step - loss: 0.0685 - accuracy: 0.9784


In [101]:
eight = Image.open('WhatsApp Image 2023-08-25 at 4.00.40 PM.jpeg') #WhatsApp Image 2023-08-25 at 4.00.40 PM= file name
eight

In [102]:
image = eight.convert("L")

# Save the grayscale image
image.save("grayscale_eight.jpg")

In [103]:
eight_grey = Image.open('grayscale_eight.jpg')
arr = np.asarray(eight_grey)
arr

array([[  0,   0,   0,   0,   0,   0,   0,   0,   3,  10,   0,   0,   8,
         15,   1,   1,   2,   0,  18,   0,   6,   0,   0,   8,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   1,   0,  34,   0,   3,
          0,   0,   8,  14,   6,   0,   0,   9,  10,   2,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  11,   0, 255, 254,
        255, 255, 238, 232,  14,   0,  15,   1,   0,  15,   2,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   4,   0, 241, 255,   0,
          0,   8,  12, 255, 246,  13,   0,  18,   6,   0,   2,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 255, 255,   7,   5,
          6,   0,   0,   0, 255,   0,   1,   0,  10,   0,   4,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 255, 230,   0,   0,   0,
          2,   0,   9,   7,   2, 251,   2,  13,   0,   0,   2,   0,   0,
          0,   0],
       [  

In [98]:
arr.shape

(28, 28)

In [104]:
arr784 = arr.reshape(1,784) #for convert in2D

In [105]:
model.predict(arr784)

1/1 [==============================] - 0s 18ms/step


array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)

In [106]:
np.argmax(model.predict(arr784))

1/1 [==============================] - 0s 18ms/step


7

In [91]:
#or full code in one line
np.argmax(model.predict(np.asarray(Image.open('grayscale_eight.jpg')).reshape(1,784)))

1/1 [==============================] - 0s 19ms/step


7

### for image 3

In [95]:
three = Image.open('three.jpeg') #checking model for new image
three

In [96]:
image = three.convert("L")

# Save the grayscale image
image.save("grayscale_three.jpg")

In [97]:
#or full code in one line
np.argmax(model.predict(np.asarray(Image.open('grayscale_three.jpg')).reshape(1,784)))

1/1 [==============================] - 0s 19ms/step


3